# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcer <- function(mc_seq, mc_order, uniq_states, state_space) {
    .Call(`_mcer_mcer`, mc_seq, mc_order, uniq_states, state_space)
}

lz77entropy <- function(x, window_size = 10L) {
    .Call(`_mcer_lz77entropy`, x, window_size)
}

lz77entropy_quick <- function(x, window_size = 10L) {
    .Call(`_mcer_lz77entropy_quick`, x, window_size)
}

rcpp_hello <- function() {
    .Call(`_mcer_rcpp_hello`)
}

